# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/Product Photos')),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('quantity', models.IntegerField()),
                ('catagories', models.CharField(choices=[('Pashmina', 'Pashmina'), ('Woolen', 'Woolen'), ('Silk', 'Silk'), ('Cotton', 'Cotton'), ('Hemp', 'Hemp'), ('Dhaka', 'Dhaka'), ('Metal Craft', 'Metal Craft'), ('Wood Craft', 'Wood Craft'), ('Stone Craft', 'Stone Craft'), ('Paper Product', 'Paper Product'), ('Bamboo Product', 'Bamboo Product'), ('Thanka', 'Thanka'), ('Beads Items', 'Beads Items'), ('Ceramics Products', 'Ceramics Products')], max_length=50)),
            ],
        ),
    ]
