# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catagories',
            field=models.CharField(choices=[('Pashmina', 'Pashmina'), ('Garland', 'Garland'), ('Homemade product', 'Homemade product'), ('Woolen', 'Woolen'), ('Silk', 'Silk'), ('Cotton', 'Cotton'), ('Hemp', 'Hemp'), ('Dhaka', 'Dhaka'), ('Metal Craft', 'Metal Craft'), ('Wood Craft', 'Wood Craft'), ('Stone Craft', 'Stone Craft'), ('Paper Product', 'Paper Product'), ('Bamboo Product', 'Bamboo Product'), ('Thanka', 'Thanka'), ('Beads Items', 'Beads Items'), ('Ceramics Products', 'Ceramics Products')], max_length=50),
        ),
    ]
