# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20170520_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
    ]
