# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organization', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=50)),
                ('business_type', models.CharField(choices=[('KS', 'Knitting & Stiching'), ('HNDCRFTS', 'Handicrafts'), ('OD', 'Ornament Designs'), ('DCRNTS', 'Decorations'), ('WC', 'Wood Carving'), ('AH', 'Animal Husbandary'), ('SS', 'Statue Sculpture'), ('MD', 'Mask & Dolls')], max_length=100)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_image', models.ImageField(upload_to='Product Photos')),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
    ]
